package madlibsprompt

var basicObjects = []string{
	"painting",
	"sculpture",
	//"drawing",
	"photography",
	"object d'art",
	//"archeological finding",
}

// var artObjects = []string{
// 	"petroglyph",
// 	"altarpiece",
// 	"amphora",
// 	"amulet",
// 	"armor",
// 	"artifact",
// 	"astrolabe",
// 	"bench",
// 	"bio-art",
// 	"bonsai",
// 	"book",
// 	"bible",
// 	"book of the dead",
// 	"vessel",
// 	"bust",
// 	"cabinet",
// 	"calligraphy sample",
// 	"candelabra",
// 	"canopic jar",
// 	"carving",
// 	"celadon",
// 	"censer",
// 	"ceramics",
// 	"chair",
// 	"chalice",
// 	"chandelier",
// 	"chest",
// 	"clock",
// 	"cloisonné",
// 	"codex",
// 	"coffin",
// 	"coin",
// 	"collage",
// 	"column",
// 	"compass",
// 	"costume",
// 	"crosier",
// 	"cuneiform tablet",
// 	"cylinder seal",
// 	"dagger",
// 	"delft ceramic",
// 	"desk",
// 	"diary",
// 	"diptych",
// 	"drawing",
// 	"embroidery",
// 	"enamelwork",
// 	"engraving",
// 	"epitaph",
// 	"etching",
// 	"Fabergé Egg",
// 	"fabric",
// 	"figurine",
// 	"film",
// 	"fountain",
// 	"fresco",
// 	"furniture",
// 	"garment",
// 	"helmet",
// 	"hieroglyph",
// 	"icon",
// 	"idol",
// 	"ikebana",
// 	"manuscript",
// 	"illustration",
// 	"insignia",
// 	"installation",
// 	"interactive art",
// 	"jade carving",
// 	"jewelry",
// 	"achina Doll",
// 	"kimono",
// 	"kinetic sculpture",
// 	"Lacquerware",
// 	"lamp",
// 	"landscape",
// 	"letter",
// 	"light art",
// 	"manuscript",
// 	"map",
// 	"mask",
// 	"medal",
// 	"Meissen porcelain",
// 	"metalwork",
// 	"mirror",
// 	"Moai",
// 	"monument",
// 	"mosaic",
// 	"mummy",
// 	"mural",
// 	"obelisk",
// 	"painting",
// 	"papyrus",
// 	"performance piece",
// 	"photograph",
// 	"pillar",
// 	"porcelain",
// 	"portrait",
// 	"postcard",
// 	"pottery",
// 	"print",
// 	"record",
// 	"relic",
// 	"reliefs",
// 	"bas-relief",
// 	"reliquary",
// 	"weapon",
// 	"runestone",
// 	"sarcophagus",
// 	"satue",
// 	"scepter",
// 	"scroll",
// 	"sculpture",
// 	"shield",
// 	"sketch",
// 	"soapstone carving",
// 	"sphinx",
// 	"stained glass",
// 	"statuette",
// 	"Stelae",
// 	"stele",
// 	"stone",
// 	"stone carving",
// 	"sundial",
// 	"sword",
// 	"table",
// 	"tape",
// 	"tapestry",
// 	"textile",
// 	"Tiffany lamp",
// 	"tombstone",
// 	"totem",
// 	"totem pole",
// 	"triptych",
// 	"urn",
// 	"ushabtis",
// 	"vase",
// 	"Venetian glass",
// 	"vestment",
// 	"video",
// 	"wardrobe",
// 	"weapon",
// 	"weavings",
// 	"woodblock print",
// 	"woodcarving",
// 	"doll",
// 	"toy",
// 	"musical instrument",
// 	"music sheet",
// }
