package madlibsprompt

// var artStyles = []string{
// 	"aboriginal",
// 	"Abramtsevo Colony",
// 	"abstract",
// 	"abstract expressionist",
// 	"abstract illusionism",
// 	"academic art",
// 	"Action painting",
// 	"Aegean art",
// 	"Aestheticism",
// 	"african",
// 	"Afrofuturism",
// 	"allegorical",
// 	"Altermodern",
// 	"American Barbizon school",
// 	"American impressionism",
// 	"American realism",
// 	"Analytical art",
// 	"Ancient Greek art",
// 	"Anglo-Saxon ",
// 	"anime",
// 	"Antipodeans",
// 	"Arabesque",
// 	"Arbeitsrat für Kunst",
// 	"Art and Language",
// 	"art brut",
// 	"art deco",
// 	"Art Informel",
// 	"art nouveau",
// 	"Art photography",
// 	"arte povera",
// 	"Arts and Crafts movement",
// 	"ASCII art",
// 	"Ashcan School",
// 	"Assemblage",
// 	"Australian Tonalism",
// 	"Auto-destructive art",
// 	"Avant-garde",
// 	"Barbizon school",
// 	"Baroque",
// 	"Bauhaus",
// 	"Bengal School of Art",
// 	"Berlin Secession",
// 	"Biedermeier",
// 	"Black Arts Movement",
// 	"Brutalism",
// 	"Byzantine",
// 	"calligraphic",
// 	"Caravaggisti",
// 	"Carolingian",
// 	"chiaroscuro",
// 	"chinese",
// 	"Classical Realism",
// 	"Cloisonnism",
// 	"Color Field",
// 	"Computer art",
// 	"Conceptual art",
// 	"Concrete art",
// 	"Constructivism",
// 	"Contemporary Greek art",
// 	"Context art",
// 	"Crystal Cubism",
// 	"Cubism",
// 	"Cubo-Futurism",
// 	"cybernetic",
// 	"Cynical realism",
// 	"Dada",
// 	"Dansaekhwa",
// 	"Danube school",
// 	"Dau-al-Set",
// 	"De Stijl",
// 	"Deconstructivism",
// 	"decorative",
// 	"Didacticism",
// 	"Digital art",
// 	"distorted",
// 	"Düsseldorf school",
// 	"Dutch Golden Age",
// 	"Early Christian",
// 	"Early Cretan School",
// 	"Early Netherlandish",
// 	"Ecological Art",
// 	"emotive",
// 	"encaustic",
// 	"Environmental art",
// 	"erotic",
// 	"Excessivism ",
// 	"Exoticism",
// 	"Expressionism",
// 	"Fantastic realism",
// 	"Fauvism",
// 	"Feminist art",
// 	"Figuration Libre",
// 	"Figurative art",
// 	"Fine Art",
// 	"Flemish Baroque",
// 	"Flemish painting",
// 	"Fluxus",
// 	"Folk art",
// 	"formalistic",
// 	"fragmented",
// 	"Funk art",
// 	"Futurism",
// 	"geometric",
// 	"Geometric abstract art",
// 	"gestural",
// 	"Glitch art",
// 	"Gothic",
// 	"Graffiti",
// 	"Gutai group",
// 	"Hague School",
// 	"Happening",
// 	"Harlem Renaissance",
// 	"Heidelberg School",
// 	"hellenistic",
// 	"Heptanese School",
// 	"Hudson River School",
// 	"Hudson River School",
// 	"Hurufiyya",
// 	"Hypermodernism",
// 	"Hyperrealism",
// 	"iconoclastic",
// 	"iconographic",
// 	"Impressionism",
// 	"impressionist",
// 	"Incoherents",
// 	"indian",
// 	"Installation art",
// 	"Institutional critique",
// 	"Insular art",
// 	"Interactive Art",
// 	"International Gothic",
// 	"International Typographic Style",
// 	"islamic",
// 	"Italian Renaissance",
// 	"japanese",
// 	"Japonisme",
// 	"Junk art",
// 	"Kinetic art",
// 	"Kinetic Pointillism",
// 	"Kitsch",
// 	"korean",
// 	"Land art",
// 	"Late Renaissance",
// 	"Later Cretan School",
// 	"Les Automatistes",
// 	"Les Nabis",
// 	"Letterism",
// 	"Light and Space",
// 	"Lowbrow",
// 	"Luminism",
// 	"Lyco art",
// 	"Lyrical Abstraction",
// 	"Macchiaioli",
// 	"Magic realism",
// 	"Mail art",
// 	"manga",
// 	"Mannerismism",
// 	"Massurrealism",
// 	"Maximalism",
// 	"medieval",
// 	"memento mori",
// 	"Merovingian",
// 	"Metaphysical painting",
// 	"Metarealism",
// 	"Migration Period",
// 	"Mingei",
// 	"Minimalism",
// 	"Minoan art",
// 	"Modern European ink painting",
// 	"Modern Greek art ",
// 	"Modernism",
// 	"Modular constructivism",
// 	"monochromatic",
// 	"nabis",
// 	"Naive art",
// 	"narrative",
// 	"native american",
// 	"naturalistic",
// 	"Nazarene movement",
// 	"neo-baroque",
// 	"Neo-Dada",
// 	"Neo-expressionism",
// 	"Neo-Fauvism",
// 	"Neo-figurative",
// 	"neo-futurist",
// 	"neo-Impressionist",
// 	"Neo-primitivism",
// 	"neo-Romanticism",
// 	"neo-victorian",
// 	"Neoclassicism",
// 	"Neoism",
// 	"neoplasticism",
// 	"Net art",
// 	"New Objectivity",
// 	"New realism",
// 	"New Sculpture",
// 	"Norman-Sicilian",
// 	"Northwest School",
// 	"Norwich school",
// 	"novecento italiano",
// 	"Nuclear art",
// 	"Objective abstraction",
// 	"Op Art",
// 	"orientalist",
// 	"ornamental",
// 	"Orphism",
// 	"Ottonian",
// 	"outsider art",
// 	"Painters Eleven",
// 	"Panfuturism",
// 	"Paris School",
// 	"pastoral",
// 	"Patna School of Painting",
// 	"Peredvizhniki",
// 	"Performance art",
// 	"persian",
// 	"Photorealism",
// 	"Pixel art",
// 	"Plasticien",
// 	"Plein Air",
// 	"Pointillism",
// 	"Pop Art",
// 	"Post-impressionism",
// 	"Post-minimalism",
// 	"Post-painterly abstraction",
// 	"Postminimalism",
// 	"Postmodern art",
// 	"Pre-Raphaelitism",
// 	"Pre-Romanesque ",
// 	"Precisionism",
// 	"prehistoric",
// 	"Primitivism",
// 	"Private Press",
// 	"Process art",
// 	"Psychedelic art",
// 	"Purismo",
// 	"purist",
// 	"Qajar art",
// 	"Quito School",
// 	"Rasquache",
// 	"Rayonism",
// 	"Realism",
// 	"reductive",
// 	"Regionalism",
// 	"religious",
// 	"Renaissance",
// 	"Renaissance Classicism",
// 	"representational",
// 	"Retrofuturism",
// 	"Rococo",
// 	"Roman art",
// 	"Romanesque",
// 	"Romanticism",
// 	"sacred",
// 	"Samikshavad",
// 	"satirical",
// 	"scuola romana",
// 	"Serial art",
// 	"Shin hanga",
// 	"Shock art",
// 	"simplistic",
// 	"site-specific",
// 	"Skeuomorph",
// 	"Socialist realism",
// 	"Sōsaku hanga",
// 	"Sots Art",
// 	"Soviet Nonconformist Art",
// 	"Space art",
// 	"Spanish Eclecticism",
// 	"Street art",
// 	"Stuckism",
// 	"stylized",
// 	"Sumatraism",
// 	"Superflat",
// 	"Surrealism",
// 	"Symbolism",
// 	"Synchromism",
// 	"Synthetism",
// 	"Tachisme",
// 	"Temporary art",
// 	"Tonalism",
// 	"Toyism",
// 	"transavantgarde",
// 	"Transgressive art",
// 	"trompe l'oeil",
// 	"Ukiyo-e",
// 	"Underground comix",
// 	"Unilalianism",
// 	"Vancouver School",
// 	"Vanitas",
// 	"Verdadism",
// 	"victorian",
// 	"Video art",
// 	"Vienna School of Fantastic Realism",
// 	"Viennese Actionism",
// 	"Viking ",
// 	"Visigothic ",
// 	"visionary",
// 	"Visual Art",
// 	"Vorticism",
// 	"Woodlands School",
// 	"Young British Artists",
// 	"Aztec",
// 	"Mayan",
// 	"Inca",
// }
