package madlibsprompt

var paintPeriod = []string{
	"Ancient",
	"Medieval",
	"Renaissance",
	"Baroque",
	"Rococo",
	"Neoclassicism",
	"Romanticism",
	"Mid to Late 19th Century",
	"Avant-Garde",
	"Contemporary",
}

var midLate19th = []string{
	"Realism",
	"Impressionism",
	"Post-Impressionism",
	"Symbolism",
	"Pre-Raphaelite Brotherhood",
	"Tonalism",
	"Aestheticism",
	"Art Nouveau",
	"Barbizon School",
	"Orientalism",
	"Academic Art",
	"Naturalism",
}

var avantGarde = []string{
	"Realism",
	"Impressionism",
	"Fauvism",
	"Expressionism",
	"Cubism",
	"Futurism",
	"Abstract Art",
	"Suprematism",
	"Dada",
	"De Stijl",
	"Surrealism",
	"Constructivism",
	"Bauhaus",
	"New Objectivity",
}

var contemporary = []string{
	"Abstract Expressionism",
	"Color Field Painting",
	"Pop Art",
	"Op Art",
	"Hard-Edge Painting",
	"Minimalism",
	"Lyrical Abstraction",
	"Post-Painterly Abstraction",
	"Neo-Dada",
	"Photorealism",
	"Fluxus",
	"Conceptual Art",
	"Postmodernism",
	"Neo-Expressionism",
	"Street Art",
	"Graffiti Art",
	"Installation Art",
	"Conceptual Art",
	"Transavantgarde",
	"Hyperrealism",
	"Figurative Art",
	"Photorealism",
	"Environmental Art",
	"Land Art",
	"Interactive Art",
	"Relational Aesthetics",
	"Deconstructivism",
	"Bio Art",
}

var paintMedia = []string{
	//ancient
	"Pigment on Plaster",
	"Encaustic on Panel",
	"Tempera on Wood",
	//medieval
	"Manuscript Illumination and Gold Leaf on Parchment",
	"Egg Tempera on Wood",
	"Fresco on Plaster",
	"Tempera Panel Painting",
	//rennaissance
	"Oil on Panel",
	"Oil on Canvas",
	"Tempera on Panel",
	"Sgraffito",
	//baroque
	"Oil on Canvas",
	"Oil on Copper",
	"Oil on Wood",
	"Oil on Slate",
	"Oil on Marble",
	//19thcent
	"Oil on Canvas",
	"Tempera on Panel",
	"Fresco on Plaster",
	"Watercolor on Paper",
	"Gouache on Paper",
	//modern
	"Oil on Canvas",
	"Oil on Board",
	"Mixed Media on Canvas",
	"Collage",
	"Acrylic on Canvas",
	"Silkscreen on Canvas",
	"Enamel on Canvas",
	"Natural Materials",
	//contemp
	"Digital Print",
	"Spray Paint on Wall",
}

var paintThemes = []string{
	"Portrait",
	"Landscape",
	"Still Life",
	"Seascape",
	"Cityscape",
	"Religious scene",
	"Mythological scene",
	"Historical scene",
	"Allegorical scene",
	"Genre Scene",
	"Artistic Nude",
	"Floral",
	"Animal portrait",
	"Marine scene",
	"Architectural scene",
	"Symbolic scene",
	"Figure Study",
	"Botanical study",
	"Interior Scene",
	"Pastoral scene",
	"Battle Scene",
	"Literary scene",
	"Decorative composition",
	"Political scene",
	"Satirical scene",
	"Narrative scene",
	"Visionary scene",
	"Panorama",
	"Mandala",
}
