package madlibsprompt

var paint_type = []string{
	"Oil Painting",
	"Watercolor Painting",
	"Acrylic Painting",
	"Gouache Painting",
	"Tempera Painting",
	"Encaustic Painting",
	"Fresco Painting",
	"Pastel Painting",
	"Spray Painting",
	"Ink Wash Painting",
	"Casein Painting",
	"Distemper Painting",
	"Enamel Painting",
	"Epoxy Painting",
	"Glass Painting",
	"Silk Painting",
	"Synthetic Resin Painting",
	"Lacquer Painting",
	"Pencil Painting",
	"Charcoal Painting",
	"Crayon Painting",
	"Marker Painting",
	"Mixed Media Painting",
	"Digital Painting",
	"Aerosol Paint Painting",
	"Polymer Paint Painting",
	"Dye Painting",
	"Varnish Painting",
	"Resin Painting",
	"Gesso Painting",
	"Milk Paint Painting",
	"Glaze Painting",
	"Ink and Brush Painting",
	"Textile Paint Painting",
	"Ceramic Paint Painting",
	"Fabric Paint Painting",
	"Leather Paint Painting",
	"Plastic Paint Painting",
	"Rubber Paint Painting",
	"Stone Paint Painting",
	"Wax Painting",
	"Metallic Paint Painting",
	"Pearlescent Paint Painting",
	"Photo-reactive Paint Painting",
	"Thermochromic Paint Painting",
	"Chalk Paint Painting",
	"Grit Paint Painting",
	"Silica Paint Painting",
	"Graphite Paint Painting",
	"Fluorescent Paint Painting",
}

var paint_media = []string{
	"Canvas",
	"Wood",
	"Paper",
	"Masonite",
	"Panel",
	"Glass",
	"Metal",
	"Ceramic",
	"Fabric",
	"Silk",
	"Linen",
	"Cardboard",
	"Stone",
	"Wall (Mural)",
	"Ivory",
	"Vellum",
	"Leather",
	"Plastic",
	"Plywood",
	"Slate",
	"Concrete",
	"Tile",
	"Brick",
	"Parchment",
	"Copper",
	"Aluminum",
	"Acrylic Sheet",
	"Hardboard",
	"Foam Board",
	"Bamboo",
	"Papyrus",
	"Marble",
	"Glassine",
	"Velvet",
	"Burlap",
	"Cork",
	"Mirror",
	"Synthetic Polymer",
	"Clayboard",
	"MDF (Medium Density Fiberboard)",
	"Recycled Materials",
	"Found Objects",
	"Silicone",
	"Vinyl",
	"Tapestry",
	"Limestone",
	"Graphite Board",
	"Chipboard",
	"Mesh",
	"Sandstone",
}

var paint_themes = []string{
	"Portrait",
	"Landscape",
	"Still Life",
	"Seascape",
	"Cityscape",
	"Religious scene",
	"Mythological scene",
	"Historical scene",
	"Allegorical scene",
	"Genre Scene",
	"Artistic Nude",
	"Floral",
	"Animal portrait",
	"Marine scene",
	"Architectural scene",
	"Symbolic scene",
	"Figure Study",
	"Botanical study",
	"Interior Scene",
	"Pastoral scene",
	"Battle Scene",
	"Literary scene",
	"Decorative composition",
	"Political scene",
	"Satirical scene",
	"Narrative scene",
	"Visionary scene",
	"Panorama",
	"Mandala",
}

var paint_movements = []string{
	"Renaissance",
	"Baroque",
	"Rococo",
	"Neoclassicism",
	"Romanticism",
	"Realism",
	"Impressionism",
	"Post-Impressionism",
	"Symbolism",
	"Fauvism",
	"Cubism",
	"Expressionism",
	"Dada",
	"Surrealism",
	"Abstract Expressionism",
	"Pop Art",
	"Op Art",
	"Minimalism",
	"Photorealism",
	"Neo-Expressionism",
	"Mannerism",
	"Pre-Raphaelitism",
	"Hudson River School",
	"Tonalism",
	"Art Nouveau",
	"Arts and Crafts Movement",
	"Ashcan School",
	"Futurism",
	"Vorticism",
	"De Stijl",
	"Suprematism",
	"Constructivism",
	"Precisionism",
	"Regionalism",
	"Social Realism",
	"Mexican Muralism",
	"Color Field Painting",
	"Lyrical Abstraction",
	"Hard-edge Painting",
	"Conceptual Art",
	"Gutai Group",
	"CoBrA",
	"Transavantgarde",
	"Bad Painting",
	"New Leipzig School",
	"Street Art",
	"Stencil Art",
	"Figurative Art",
	"Magic Realism",
	"Hyperrealism",
}
