package madlibsprompt

var sculpt_types = []string{
	"Statue",
	"Bust",
	"Relief",
	"Figurine",
	"Monument",
	"Equestrian Statue",
	"Torso",
	"Carving",
	"Casting",
	"Modeling",
	"Assemblage",
	"Installation",
	"Kinetic Sculpture",
	"Mobile",
	"Stabile",
	"Environmental Sculpture",
	"Land Art",
	"Public Art",
	"Garden Sculpture",
	"Architectural Sculpture",
	"Memorial",
	"Fountain Sculpture",
	"Abstract Sculpture",
	"Geometric Sculpture",
	"Organic Sculpture",
	"Interactive Sculpture",
	"Statuette",
	"Funerary Sculpture",
	"Micro Sculpture",
	"Macquette",
	"Large-Scale Sculpture",
	"Site-Specific Sculpture",
	"Wearable Sculpture",
	"Functional Sculpture",
	"Miniature Sculpture",
	"Street Sculpture",
	"Decorative Sculpture",
	"Symbolic Sculpture",
	"Conceptual Sculpture",
}

var sculpt_material = []string{
	"Marble",
	"Terracotta",
	"Glass",
	"Bronze",
	"Wood",
	"Stone",
	"Clay",
	"Plaster",
	"Metal",
	"Steel",
	"Iron",
	"Concrete",
	"Granite",
	"Limestone",
	"Sandstone",
	"Alabaster",
	"Ivory",
	"Gold",
	"Silver",
	"Copper",
	"Brass",
	"Lead",
	"Zinc",
	"Tin",
	"Resin",
	"Fiberglass",
	"Plastic",
	"Acrylic",
	"Epoxy",
	"Wax",
	"Papier-Mâché",
	"Ceramic",
	"Porcelain",
	"Silicon",
	"Rubber",
	"Bamboo",
	"Coral",
	"Bone",
	"Shell",
	"Textile",
	"Leather",
	"Cardboard",
	"Foam",
	"Foam Board",
	"Jade",
	"Obsidian",
	"Plexiglass",
	"Mosaic Tiles",
	"Sand",
	"Ice",
}

var sculpt_movements = []string{
	"Classical Greek Sculpture",
	"Hellenistic Sculpture",
	"Roman Sculpture",
	"Gothic Sculpture",
	"Renaissance Sculpture",
	"Baroque Sculpture",
	"Rococo Sculpture",
	"Neoclassical Sculpture",
	"Romantic Sculpture",
	"Realist Sculpture",
	"Symbolist Sculpture",
	"Art Nouveau Sculpture",
	"Modernist Sculpture",
	"Cubist Sculpture",
	"Futurist Sculpture",
	"Constructivist Sculpture",
	"Dada Sculpture",
	"Surrealist Sculpture",
	"Abstract Expressionist Sculpture",
	"Minimalist Sculpture",
	"Pop Art Sculpture",
	"Op Art Sculpture",
	"Kinetic Art",
	"Land Art",
	"Environmental Sculpture",
	"Conceptual Sculpture",
	"Installation Art",
	"Assemblage",
	"Social Realist Sculpture",
	"Post-Minimalist Sculpture",
	"Process Art",
	"Hyperrealist Sculpture",
	"Neo-Expressionist Sculpture",
	"Feminist Art",
	"Public Art",
	"Street Art Sculpture",
	"Graffiti Art Sculpture",
	"Bio Art",
	"Light Art",
	"Sound Art",
	"Digital Sculpture",
	"Virtual Reality Art",
	"New Media Art",
	"Interactive Art",
	"Relational Art",
	"Transgressive Art",
	"Performance Art",
	"Symbolic Sculpture",
	"Visionary Art",
	"Found Object Art",
}
