package madlibsprompt

var subgenres = []string{
	"Gothic Fantasy",
	"Urban Fantasy",
	"Dark Urban Fantasy",
	"Sword and Sorcery",
	"Mythic Fantasy",
	"Paranormal Fantasy",
	"Grimdark",
	"Dark Epic Fantasy",
	"Occult Fantasy",
	"Supernatural Fantasy",
	"Vampire Fantasy",
	"Necromantic Fantasy",
	"Apocalyptic Fantasy",
	"Lovecraftian Fantasy",
	"Weird Western Fantasy",
	"Dark Fairy Tales",
	"Demon Fantasy",
	"Ghost Fantasy",
	"Eldritch Fantasy",
	"Dark Portal Fantasy",
	"Gothic Horror",
	"Psychological Horror",
	"Paranormal Horror",
	"Supernatural Horror",
	"Occult Horror",
	"Splatterpunk",
	"Body Horror",
	"Slasher Horror",
	"Monster Horror",
	"Vampire Horror",
	"Werewolf Horror",
	"Zombie Horror",
	"Cosmic Horror",
	"Lovecraftian Horror",
	"Survival Horror",
	"Folk Horror",
	"Historical Horror",
	"Crime Horror",
	"Techno-Horror",
	"Dark Romantic Horror",
	"Soft Science Fiction",
	"Space Exploration",
	"Alternate History",
	"Steampunk",
	"Dieselpunk",
	"Atompunk",
	"Cyberpunk",
	"Biopunk",
	"Solar Punk",
	"Space Opera",
	"Science Fantasy",
	"Dystopian",
	"Utopian",
	"Post-Apocalyptic",
	"Alien Invasion",
	"First Contact",
	"Time Travel",
	"Multiverse",
	"Genetic Engineering",
	"AI and Robotics",
	"Climate Fiction",
	"Space Western",
	"Heroic Science Fiction",
	"Mythic Realism",
	"Fantastique",
	"Surrealism",
	"Urban Magical Realism",
	"Literary Magical Realism",
	"Historical Magical Realism",
	"Postcolonial Magical Realism",
	"Folklore Magical Realism",
	"Cultural Magical Realism",
	"Feminist Magical Realism",
	"Gothic Magical Realism",
	"Political Magical Realism",
	"Pastoral Magical Realism",
	"Metaphysical Magical Realism",
	"Contemporary Magical Realism",
	"Mythopoetic Realism",
	"Philosophical Magical Realism",
	"Allegorical Magical Realism",
	"Ecological Magical Realism",
	"Visionary Magical Realism",
	"Supernatural Weird Fiction",
	"Cosmic Weird Fiction",
	"Psychological Weird Fiction",
	"Occult Weird Fiction",
	"Mythic Weird Fiction",
	"Alien Weird Fiction",
	"Lovecraftian Weird Fiction",
	"New Weird",
	"Gothic Weird Fiction",
	"Surreal Weird Fiction",
	"Slipstream",
	"Bizarro Fiction",
	"Dark Weird Fiction",
	"Experimental Weird Fiction",
	"Fantasy Weird Fiction",
	"Horror Weird Fiction",
	"Apocalyptic Weird Fiction",
	"Detective Weird Fiction",
	"Noir Weird Fiction",
	"Mythos Fiction",
}

var generalMood = []string{
	"fear",
	"awe",
	"wonder",
	"curiosity",
	"suspense",
	"obsession",
	"horror",
	"anxiety",
	"marvel",
	"ecstasy",
	"nostalgia",
	"intrigue",
	"foreboding",
	"euphoria",
	"melancholy",
	"astonishment",
	"fascination",
	"bewilderment",
	"enigma",
	"yearning",
	"disquiet",
	"unease",
	"joy",
	"thrill",
	"zeal",
	"hope",
	"mystery",
	"glee",
	"amazement",
	"delight",
	"enthusiasm",
	"sorrow",
	"shock",
	"isolation",
	"sorrow",
	"envy",
	"resentment",
	"regret",
	"relief",
	"contempt",
	"pity",
	"distress",
	"alarm",
	"gloom",
	"desperation",
	"serenity",
	"zeal",
	"morbidity",
	"torment",
	"bliss",
}

var protagonists = []string{
	"author of the artwork - The creator of this particular piece",
	"curator - An experienced curator who discovers a mysterious artifact",
	"archaeologist - A passionate archaeologist on the trail of a legendary relic",
	"historian - A historian unraveling the secrets of an ancient artifact",
	"art restorer - An art restorer uncovering hidden layers of a centuries-old painting",
	"collector - An eccentric collector who acquires a cursed object",
	"museum guard - A night guard encountering strange occurrences",
	"visitor - A curious visitor drawn to an enigmatic exhibit",
	"student - A graduate student researching a rare artifact for their thesis",
	"conservator - A conservator tasked with preserving a fragile, mystical item",
	"thief - A thief with a hidden motive stealing a powerful relic",
	"anthropologist - An anthropologist discovering a piece with ties to an ancient civilization",
	"librarian - A librarian stumbling upon a forgotten piece with a dark history",
	"time traveler - A time traveler who places an item in the museum",
	"detective - A detective investigating a crime involving a stolen artifact",
	"explorer - An explorer uncovering a lost artifact from an unknown land",
	"scientist - A scientist analyzing the properties of an extraordinary find",
	"historian of the future - A historian from a future civilization studying ancient artifacts",
	"reporter - A reporter covering a mysterious event related to a museum piece",
	"child - A child with a unique connection to a magical object",
	"ghost - A ghost tied to an artifact seeking resolution",
	"artist - An artist inspired by or haunted by a particular exhibit",
	"mage - A mage discovering an artifact with hidden powers",
	"inventor - An inventor whose creation ends up in the museum",
	"psychic - A psychic sensing the residual energy of a powerful artifact",
	"historian's assistant - An assistant who stumbles upon something their boss overlooked",
	"guardian - A mythical guardian sworn to protect a sacred artifact",
	"intern - A museum intern uncovering a hidden secret",
	"philanthropist - A philanthropist funding the acquisition of a mysterious piece",
	"forger - An art forger discovering a real artifact among fakes",
	"archivist - An archivist cataloging an unmarked artifact with a dark history",
	"exorcist - An exorcist called in to deal with a haunted object",
	"historian's rival - A rival historian trying to uncover secrets first",
	"undercover agent - An undercover agent investigating a theft in the museum",
	"occultist - An occultist drawn to a powerful, mystical artifact",
	"historian's descendant - A descendant of a historian finding their ancestor's lost piece",
	"heir - The heir to a family legacy involving a powerful artifact",
	"librarian from another world - A librarian from a parallel universe researching the artifact",
	"alien - An alien studying human history through artifacts",
	"ancient guardian - An ancient being awakening to protect its artifact",
	"curse breaker - A specialist in breaking curses tied to artifacts",
	"historian of the supernatural - A historian specializing in supernatural items",
	"curator's apprentice - An apprentice learning the trade while uncovering secrets",
	"immortal - An immortal being connected to a timeless artifact",
	"mystic - A mystic interpreting the significance of a powerful piece",
	"historian's mentor - An experienced mentor guiding a young historian",
	"relic hunter - A professional relic hunter searching for legendary items",
	"dreamer - A dreamer experiencing visions connected to a museum piece",
	"guardian spirit - A spirit bound to protect an ancient artifact",
	"historian of lost civilizations - A historian focused on lost civilizations",
	"mystery author - An author who finds inspiration and danger in a museum piece",
	"Ravensfield family member - The person from the Ravensfield family who added this piece to the collection",
	"average person - Someone who encountered the artwork by chance and suffered the consequences",
}

var themes = []string{
	"wild creativity",
	"artistic obsession",
	"existential dread",
	"professional jealousy",
	"societal envy",
	"rise and fall",
	"love gone wrong",
	"tragic love",
	"creativity into madness",
	"seeing through the veil",
	"the afterlife",
	"things that crawl at night",
	"tapping into other realities",
	"ancient gods",
	"the mythical and the mundane",
	"the forbidden",
	"lost civilizations",
	"the arcane",
	"hidden magic",
	"forbidden romance",
	"supernatural seduction",
	"beyond the senses",
	"forbidden knowledge",
	"unseen forces",
	"curses and blessings",
	"betrayal",
	"redemption",
	"time and memory",
	"the cost of immortality",
	"the power of belief",
	"unreliable reality",
	"inner demons",
	"the haunted past",
	"transformation",
	"the search for truth",
	"sacrifice",
	"the unknown",
	"unlikely alliances",
	"the power of artifacts",
	"the supernatural in everyday life",
	"the struggle for power",
	"the clash of worlds",
	"unintended consequences",
	"the lure of the forbidden",
	"echoes of the past",
	"the price of ambition",
	"hidden histories",
	"the quest for identity",
	"the duality of human nature",
	"mysteries of the mind",
	"the pursuit of perfection",
	"the intersection of science and magic",
	"the illusion of control",
	"surviving the impossible",
	"the collision of fate and free will",
	"secrets of the universe",
	"the fragility of sanity",
	"darkness within light",
	"the uncharted and unknown",
	"guardians of secrets",
	"the line between genius and madness",
	"the power of dreams",
}

var fates = []string{
	"disappears",
	"triumphs",
	"fails",
	"transcends",
	"goes mad",
	"falls in love",
	"commits a crime",
	"travels",
	"is trapped",
	"reaches freedom",
	"wins",
	"loses",
	"comes to an alarming realization",
	"reaches enlightment",
	"is still alive",
	"died under mysterious circumstances",
	"is murderd",
	"falls into ruin",
	"gets famous",
	"becomes infamous",
	"time-hops",
	"becomes a prophet",
	"wins his place in history",
	"is heart-broken",
	"gains supernatural insight",
	"lives a burning passion",
	"becomes obsessed",
	"lives a dream",
	"suffers a nightmare",
	"dooms himself",
	"becomes a saviour",
	"becomes part of the artwork",
	"reaches other planes of existence",
	"is cursed",
	"redeems themselves",
	"betrays someone close",
	"is betrayed",
	"vanishes without a trace",
	"is resurrected",
	"becomes immortal",
	"is forgotten by history",
	"becomes a martyr",
	"loses their identity",
	"finds a hidden family secret",
	"becomes consumed by guilt",
	"makes an impossible choice",
	"enters a pact with dark forces",
	"escapes destiny",
	"is erased from time",
	"creates a legacy",
	"falls into eternal sleep",
	"lives multiple lifetimes",
	"fades into legend",
	"transforms into a monster",
	"reverts to childhood",
	"becomes the villain",
	"sacrifices everything",
	"becomes someone else’s obsession",
	"is hunted",
	"is imprisoned beyond time",
	"returns from the dead changed",
	"inherits a curse",
	"becomes a guardian of secrets",
	"unleashes chaos",
	"is trapped in an illusion",
	"writes a book that changes the world",
	"takes on a new identity",
	"becomes the keeper of forbidden knowledge",
	"falls prey to temptation",
	"finds an impossible love",
	"achieves peace at a great cost",
	"is consumed by revenge",
	"becomes a legend no one believes in",
	"takes control of their own destiny",
	"loses their soul",
	"ascends to godhood",
	"is forgotten by everyone they loved",
	"finds redemption in death",
	"becomes a guide for others",
	"is haunted by their own creation",
	"escapes into a parallel world",
	"wakes up in a different body",
	"melts into the fabric of reality",
}

// var endings = []string{
// 	"twist ending - An unexpected turn of events that changes the story's direction",
// 	"open-ended ending - Leaving some questions unanswered, allowing readers to speculate",
// 	"happy ending - The protagonist achieves his goal or finds happiness",
// 	"tragic ending - The story concludes with sorrow or loss",
// 	"bittersweet ending - A mix of positive and negative outcomes",
// 	"cliffhanger - Ending with unresolved events, creating anticipation for a sequel",
// 	"poetic justice ending - Characters get what they deserve, in a fitting manner",
// 	"ambiguous ending - Open to interpretation, leaving the true conclusion unclear",
// 	"cyclical ending - The story ends where it began, suggesting a cycle",
// 	"moral ending - Conveying a clear moral or lesson",
// 	"redemptive ending - A character redeems themselves or is forgiven",
// 	"surprise ending - An unforeseen conclusion that shocks the reader",
// 	"reflective ending - Characters reflect on their journey and growth",
// 	"hopeful ending - Ending on a note of optimism for the future",
// 	"unsolved mystery ending - Indicating that the story's mystery remains unsolved",
// 	"revelation ending - A major revelation changes the understanding of the story",
// 	"peaceful ending - Concluding with a sense of peace and calm",
// 	"heroic sacrifice - A character sacrifices themselves for the greater good",
// 	"full circle ending - The protagonist ends up in a similar situation as the beginning but with changed circumstances",
// 	"transformation ending - A character undergoes a significant transformation or change",
// 	"new beginning - Hinting at a new chapter or adventure for the characters",
// 	"eternal struggle - Indicating that the conflict will continue indefinitely",
// 	"resolution through destruction - Ending with the destruction of key elements or characters",
// 	"fading away ending - The story quietly fades out, leaving a lasting impression",
// }
