package madlibsprompt

var generalMood = []string{
	"Fear",
	"Awe",
	"Wonder",
	"Curiosity",
	"Suspense",
	"Obsession",
	"Horror",
	"Anxiety",
	"Marvel",
	"Ecstasy",
	"Nostalgia",
	"Intrigue",
	"Foreboding",
	"Euphoria",
	"Melancholy",
	"Astonishment",
	"Fascination",
	"Bewilderment",
	"Enigma",
	"Yearning",
	"Disquiet",
	"Unease",
	"Joy",
	"Thrill",
	"Zeal",
	"Hope",
	"Mystery",
	"Glee",
	"Amazement",
	"Delight",
	"Enthusiasm",
	"Sorrow",
	"Shock",
	"Isolation",
	"Sorrow",
	"Envy",
	"Resentment",
	"Regret",
	"Relief",
	"Contempt",
	"Pity",
	"Distress",
	"Alarm",
	"Gloom",
	"Desperation",
	"Serenity",
	"Zeal",
	"Morbidity",
	"Torment",
	"Bliss",
}

var protagonists = []string{
	"Author of the artwork - The creator of this particular piece",
	"Curator - An experienced curator who discovers a mysterious artifact",
	"Archaeologist - A passionate archaeologist on the trail of a legendary relic",
	"Historian - A historian unraveling the secrets of an ancient artifact",
	"Art Restorer - An art restorer uncovering hidden layers of a centuries-old painting",
	"Collector - An eccentric collector who acquires a cursed object",
	"Museum Guard - A night guard encountering strange occurrences",
	"Visitor - A curious visitor drawn to an enigmatic exhibit",
	"Student - A graduate student researching a rare artifact for their thesis",
	"Conservator - A conservator tasked with preserving a fragile, mystical item",
	"Thief - A thief with a hidden motive stealing a powerful relic",
	"Anthropologist - An anthropologist discovering a piece with ties to an ancient civilization",
	"Librarian - A librarian stumbling upon a forgotten piece with a dark history",
	"Time Traveler - A time traveler who places an item in the museum",
	"Detective - A detective investigating a crime involving a stolen artifact",
	"Explorer - An explorer uncovering a lost artifact from an unknown land",
	"Scientist - A scientist analyzing the properties of an extraordinary find",
	"Historian of the Future - A historian from a future civilization studying ancient artifacts",
	"Reporter - A reporter covering a mysterious event related to a museum piece",
	"Child - A child with a unique connection to a magical object",
	"Ghost - A ghost tied to an artifact seeking resolution",
	"Artist - An artist inspired by or haunted by a particular exhibit",
	"Mage - A mage discovering an artifact with hidden powers",
	"Inventor - An inventor whose creation ends up in the museum",
	"Psychic - A psychic sensing the residual energy of a powerful artifact",
	"Historian's Assistant - An assistant who stumbles upon something their boss overlooked",
	"Guardian - A mythical guardian sworn to protect a sacred artifact",
	"Intern - A museum intern uncovering a hidden secret",
	"Philanthropist - A philanthropist funding the acquisition of a mysterious piece",
	"Forger - An art forger discovering a real artifact among fakes",
	"Archivist - An archivist cataloging an unmarked artifact with a dark history",
	"Exorcist - An exorcist called in to deal with a haunted object",
	"Historian's Rival - A rival historian trying to uncover secrets first",
	"Undercover Agent - An undercover agent investigating a theft in the museum",
	"Occultist - An occultist drawn to a powerful, mystical artifact",
	"Historian's Descendant - A descendant of a historian finding their ancestor's lost piece",
	"Heir - The heir to a family legacy involving a powerful artifact",
	"Librarian from Another World - A librarian from a parallel universe researching the artifact",
	"Alien - An alien studying human history through artifacts",
	"Ancient Guardian - An ancient being awakening to protect its artifact",
	"Curse Breaker - A specialist in breaking curses tied to artifacts",
	"Historian of the Supernatural - A historian specializing in supernatural items",
	"Curator's Apprentice - An apprentice learning the trade while uncovering secrets",
	"Immortal - An immortal being connected to a timeless artifact",
	"Mystic - A mystic interpreting the significance of a powerful piece",
	"Historian's Mentor - An experienced mentor guiding a young historian",
	"Relic Hunter - A professional relic hunter searching for legendary items",
	"Dreamer - A dreamer experiencing visions connected to a museum piece",
	"Guardian Spirit - A spirit bound to protect an ancient artifact",
	"Historian of Lost Civilizations - A historian focused on lost civilizations",
	"Mystery Author - An author who finds inspiration and danger in a museum piece",
	"Ravensfield family member - The person from the Ravensfield family who added this piece to the collection",
	"Average person - Someone who encountered the artwork by chance and suffered the consequences",
}

var themes = []string{
	"wild creativity",
	"artistic obsession",
	"existential dread",
	"professional jealousy",
	"societal envy",
	"rise and fall",
	"love gone wrong",
	"tragic love",
	"creativity into madness",
	"seeing through the veil",
	"the afterlife",
	"things that crawl at night",
	"tapping into other realities",
	"ancient gods",
	"the mythical and the mundane",
	"the forbidden",
	"lost civilizations",
	"the arcane",
	"hidden magic",
	"forbidden romance",
	"supernatural seduction",
	"beyond the senses",
	"Forbidden knowledge",
	"Unseen forces",
	"Curses and blessings",
	"Betrayal",
	"Redemption",
	"Time and memory",
	"The cost of immortality",
	"The power of belief",
	"Unreliable reality",
	"Inner demons",
	"The haunted past",
	"Transformation",
	"The search for truth",
	"Sacrifice",
	"The unknown",
	"Unlikely alliances",
	"The power of artifacts",
	"The supernatural in everyday life",
	"The struggle for power",
	"The clash of worlds",
	"Unintended consequences",
	"The lure of the forbidden",
	"Echoes of the past",
	"The price of ambition",
	"Hidden histories",
	"The quest for identity",
	"The duality of human nature",
	"Mysteries of the mind",
	"The pursuit of perfection",
	"The intersection of science and magic",
	"The illusion of control",
	"Surviving the impossible",
	"The collision of fate and free will",
	"Secrets of the universe",
	"The fragility of sanity",
	"Darkness within light",
	"The uncharted and unknown",
	"Guardians of secrets",
	"The line between genius and madness",
	"The power of dreams",
}

var fates = []string{
	"disappears",
	"triumphs",
	"fails",
	"transcends",
	"goes mad",
	"falls in love",
	"commits a crime",
	"travels",
	"is trapped",
	"reaches freedom",
	"wins",
	"loses",
	"comes to an alarming realization",
	"reaches enlightment",
	"is still alive",
	"died under mysterious circumstances",
	"is murderd",
	"falls into ruin",
	"gets famous",
	"becomes infamous",
	"time-hops",
	"becomes a prophet",
	"wins his place in history",
	"is heart-broken",
	"gains supernatural insight",
	"lives a burning passion",
	"becomes obsessed",
	"lives a dream",
	"suffers a nightmare",
	"dooms himself",
	"becomes a saviour",
	"becomes part of the artwork",
	"reaches other planes of existence",
}

var endings = []string{
	"Twist Ending - An unexpected turn of events that changes the story's direction",
	"Open-Ended - Leaving some questions unanswered, allowing readers to speculate",
	"Happy Ending - The protagonist achieves their goal or finds happiness",
	"Tragic Ending - The story concludes with sorrow or loss",
	"Bittersweet Ending - A mix of positive and negative outcomes",
	"Cliffhanger - Ending with unresolved events, creating anticipation for a sequel",
	"Poetic Justice - Characters get what they deserve, in a fitting manner",
	"Resolution - Tying up all loose ends and providing closure",
	"Ambiguous Ending - Open to interpretation, leaving the true conclusion unclear",
	"Cyclical Ending - The story ends where it began, suggesting a cycle",
	"Moral Ending - Conveying a clear moral or lesson",
	"Redemptive Ending - A character redeems themselves or is forgiven",
	"Surprise Ending - An unforeseen conclusion that shocks the reader",
	"Reflective Ending - Characters reflect on their journey and growth",
	"Hopeful Ending - Ending on a note of optimism for the future",
	"Mystery Continues - Indicating that the story's mystery remains unsolved",
	"Revelation Ending - A major revelation changes the understanding of the story",
	"Peaceful Ending - Concluding with a sense of peace and calm",
	"Heroic Sacrifice - A character sacrifices themselves for the greater good",
	"Full Circle Ending - The protagonist ends up in a similar situation as the beginning but with changed circumstances",
	"Transformation Ending - A character undergoes a significant transformation or change",
	"New Beginning - Hinting at a new chapter or adventure for the characters",
	"Eternal Struggle - Indicating that the conflict will continue indefinitely",
	"Resolution Through Destruction - Ending with the destruction of key elements or characters",
	"Fading Away - The story quietly fades out, leaving a lasting impression",
}
