// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package museum_db

import (
	"database/sql"
)

type ArtMuseum struct {
	ID      int64
	Mood    sql.NullString
	Style   sql.NullString
	Artwork sql.NullString
}
