// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: select-random-artwork.sql

package museum_db

import (
	"context"
	"database/sql"
)

const selectRandArtwork = `-- name: SelectRandArtwork :one
SELECT artwork
FROM art_museum
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) SelectRandArtwork(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, selectRandArtwork)
	var artwork sql.NullString
	err := row.Scan(&artwork)
	return artwork, err
}
