// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: select-random-style.sql

package museum_db

import (
	"context"
	"database/sql"
)

const selectRandStyle = `-- name: SelectRandStyle :one
SELECT style
FROM art_museum
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) SelectRandStyle(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, selectRandStyle)
	var style sql.NullString
	err := row.Scan(&style)
	return style, err
}
