// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: select-random-mood.sql

package museum_db

import (
	"context"
	"database/sql"
)

const selectRandMood = `-- name: SelectRandMood :one
SELECT mood
FROM art_museum
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) SelectRandMood(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, selectRandMood)
	var mood sql.NullString
	err := row.Scan(&mood)
	return mood, err
}
