name: ci

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: "1.22.0"
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: go test ./... -race -cover

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...

  style:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: "1.22.0"
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Check formatting
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

  deploy:
    needs: [tests, style]
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Fly deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl secrets set \
            FLY_API_TOKEN="${{ secrets.FLY_API_TOKEN }}" \
            MASTER_KEY="${{secrets.MASTER_KEY}}" \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            GHOST_KEY="${{ secrets.GHOST_ADMIN_API_KEY }}" \
            GHOST_URL="${{ secrets.GHOST_ADMIN_API_URL }}" \
            LEONARDO_KEY="${{ secrets.LEONARDO_KEY }}" \
            CLAUDE_KEY="${{secrets.CLAUDE_KEY}}" \
            CLOUDINARY_URL="${{secrets.CLOUDINARY_URL}}"

          flyctl deploy --remote-only

  # theme:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4

  #     - name: Use Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "18"
  #         check-latest: true

  #     - name: Install Yarn
  #       run: npm install -g yarn

  #     - name: Install Dependencies
  #       run: |
  #         cd themes/source-ravens
  #         yarn install

  #     - name: Run build
  #       run: |
  #         cd themes/source-ravens
  #         yarn build

  #     - name: Deploy Ghost Theme
  #       uses: TryGhost/action-deploy-theme@v1
  #       with:
  #         api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
  #         api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
  #         working-directory: themes/source-ravens
