name: Schedule Image Generation

on:
  # schedule:
  #   - cron: "0 0,1,2 * * *"
  workflow_dispatch: {}

jobs:
  build:
    name: Generate Images
    runs-on: ubuntu-latest
    steps:
      - name: Ping generator endpoint
        run: |
          curl \
          --request POST \
          -H "Accept: application/json" \
          -H "Api-Key: ${{secrets.MASTER_KEY }}" \
          https://api.ravensfield.art/img-gen
